keymap:
  - name: Terminal Overrides
    application:
      only: kitty
    remap:
      Alt-c: C-right
      Ctrl-f: C-right
      Alt-v: Alt-v

  - name: Global Remaps
    remap:
      Alt-x: C-x
      Alt-c: C-c
      Alt-v: C-v
      Alt-a: C-a
      Alt-f: C-f
      Alt-r: C-r
      Alt-z: C-z
      Alt-s: C-s
